image: ruby:2.3

compile:
  stage: "build"
  only:
    - marbetschar
  script:
    - apt-get update >/dev/null
    - curl -sL https://deb.nodesource.com/setup_7.x | bash -
    - apt-get install -y nodejs >/dev/null
    - bin/setup
    - bin/deploy

pages:
  stage: "deploy"
  only:
    - gh-pages
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - .