---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _my_tags
  label: My tags
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: _assets/images/uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
